# Generated by Django 2.2.27 on 2022-04-20 23:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220421_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='images.jpg', upload_to='images/', verbose_name='Путь к картинке'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 4, 21, 2, 37, 10, 886812), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 21, 2, 37, 10, 887812), verbose_name='Time published'),
        ),
    ]
